- name: Installing and uninstalling packages with loops
  hosts: localhost
  become: yes
  tasks: 
  - name: install
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'nginx', state: 'present'}
    - {name: 'postfix', state: 'absent'}
