- name: Installing packages with loops
  hosts: localhost
  become: yes
  tasks: 
  - name: install
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - mysql
    - postfix
